export const refs = {
  body: document.querySelector('.body'),
  header: document.querySelector('header'),
  libNav: document.querySelector('.js-lib-menu'),
  homeNav: document.querySelector('.js-home-menu'),
  formNav: document.querySelector('.search-form'),
  libList: document.querySelector('.library-list'),
  btnHome: document.querySelector('#btn-home'),
  btnLib: document.querySelector('#btn-library'),
  filmsContainer: document.querySelector('.container'),
  backdrop: document.querySelector('.backdrop'),

  btnWatched: document.querySelector('.btn-watched'),
  btnQueue: document.querySelector('.btn-queue'),
  devContainer: document.querySelector('.development-container'),
  toggle: document.querySelector('#theme-switch-toggle'),
  filmName: document.querySelector('.film-name'),
  modal: document.querySelector('.modal'),
  cardItem: document.querySelector('.card__item'),
  cardDescription: document.querySelector('.card__description'),
  cardText: document.querySelector('.card__text'),
  footer: document.querySelector('.footer'),
};
